# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Environment variable to set the password for the PostgreSQL database
#ENV POSTGRES_PASSWORD=placeholder

# Expose the PostgreSQL port
EXPOSE 5432

# Command to start PostgreSQL service
CMD ["postgres"]